# This is the main configuration file of your Dancer2 app
# generic config

appname: "PLN::PT::api"
behind_proxy: 1
layout: "main"
charset: "UTF-8"
template: "simple"

qaptnet_backend: 'http://localhost:7777'

