# configuration file for production environment

# only log warning and error messsages
log: "warning"

# log message to a file in logs/
logger: "file"

# don't consider warnings critical
warnings: 0

# hide errors
show_errors: 0

# disable server tokens in production environments
no_server_tokens: 1

# Service specific configuration

# Directory to create temporary files
TMPDIR: '/tmp/api.pln.pt'

# FreeLing4 analyze bin file
FL4BIN: '/opt/freeling-4.0/bin/analyze'

# FreeLing4 full path to config files per lang
FL4CFG:
  PT: '/opt/freeling-4.0/share/freeling/config/pt.cfg'
  GL: '/opt/freeling-4.0/share/freeling/config/gl.cfg'

SYNTAXNET:
  WRAPPER: 'bin/syntaxnet_wrapper'
  BACKEND: 'http://127.0.0.1:7000/v1/parsey-universal-full'

